### ISSUE TITLE
breaking changes from sectoralarm. 

### ISSUE THREAD

**Issue by burner-** [perbrage/sectoralarm#43]
https://mypagesapi.sectoralarm.net/ wont work anymore. So this library wont get needed information of site and all commands fail. 
Example reading info will give error TypeError: Cannot read properties of undefined (reading 'info')

**Comment by burner-** [comment]
Hmm actually it looks that api is still exist but something have changend. 

TypeError: Cannot read properties of undefined (reading 'info')
    at info (/data/node_modules/node-red-contrib-sectoralarm/lib/sectoralarm-site.js:294:20)
    at SiteNode._inputCallback (/data/node_modules/node-red-contrib-sectoralarm/lib/sectoralarm-site.js:54:21)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at SiteNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
    at SiteNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
    at SiteNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:499:10)
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:800:40)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:816:21)
    at processImmediate (node...

**Comment by Gidenskold** [comment]
Talked with Sector Alarms customer support and they confirmed that the "open" API has been closed since it caused issues with the alarm systems. They do not plan on enabling it again. The new authentication uses OAuth 2.0 and login requires a secret only known to Sector Alarm. Asked if it would be possible to generate developer credentials, which they replied that they won't do.

**Comment by burner-** [comment]
I got same kind information and I have project to terminate all sector alarm contracts and change to another vendor. Previously I recommend sectoralarm to everyone but after they did that I recommend to everyone avoid it.

**Comment by sander-visser** [comment]
I got the API working fine from curl/python:

https://github.com/sander-visser/py-playground/blob/main/sector_alarm_status.py

**Comment by francisps78** [comment]
Hi @sander-visser,

Please, could you confirm that you have integrated sector alarm in home assistant? if you have it pls could you help me to do it?
thanks in advance,
Best regards

**Comment by sander-visser** [comment]
I do not have home assistant. I have it working in python. My hot water heater currently uses alarm status to descide if I need medium or hot water setting...

I never got around to HA, but should be fairly straight forward to get perbrage/sectoralarm working again...

**Comment by garnser** [comment]
See https://github.com/garnser/sector_alarm for updated API endpoints and sample of connecting.

**Comment by perbrage** [comment]
Been a long time now since I had attention to this package. 

But, from the link you guys have pasted above I can confirm that this is doable getting the token and accessing the new API-endpoints that sector alarm have implemented. I am not sure if the older endpoints is still available to use, but the new ones seems to have been re-designed. Meaning all calls and response parsing has to be reworked, whereas some of the implementations in this package I don't have the devices to even test it (could get inspiration from other packages perhaps).

Before I start any work on this, is there any other node packages available that has been updated that people have moved to? If there are new better ones, perhaps this is just something that can be deleted instead.

**Comment by burner-** [comment]
At least I am not aware of any. However if you need tester I can test. 
Also here if more information https://github.com/perbrage/sectoralarm/issues/42

**Comment by perbrage** [comment]
Ah, I should perhaps refer to this post in that thread also
